package nl.ru.ai.Interface;

public enum Tool_t {
	NULL_TOOL,
	RECTANGLE_TOOL,
	DIAMOND_TOOL,
	TRIANGLE_UP_TOOL,
	TRIANGLE_DOWN_TOOL,
	ELLIPSE_TOOL,
	LINE_TOOL,
	NEW_CANVAS_TOOL,
	MOVE_TOOL,
	DELETE_TOOL,
	PAINT_TOOL,
	BORDER_THICKER_TOOL,
	BORDER_THINNER_TOOL,
	LAYER_UP_TOOL,
	LAYER_DOWN_TOOL,
	FREE_DRAW_TOOL,
	SPECIAL_FREE_DRAW_TOOL,
	RESIZE_SHAPE_TOOL,
	TEXT_TOOL,
	IMAGE_TOOL
}
